# mysql and phpmyadmin
version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpassword
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - "TZ=Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=mysqluser
      - PMA_PASSWORD=mysqlpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - sessions:/sessions
volumes:
  mysql_data:
  sessions:

